"""init kedua

Revision ID: 0f0bff5f685f
Revises: 88291d9da7f4
Create Date: 2025-05-24 13:22:05.103489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0bff5f685f'
down_revision = '88291d9da7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
